In [1]:
import numpy as np
import pandas as pd
from datasets import load_dataset

ds1 = load_dataset("lavita/medical-qa-datasets", "all-processed")
ds2 = load_dataset("lavita/AlpaCare-MedInstruct-52k")
ds3 = load_dataset("lavita/MedREQAL")

df1 = ds1["train"].to_pandas()
df2 = ds2["train"].to_pandas()
df3 = ds3["train"].to_pandas()

print("Dataset1 columns:", df1.columns.tolist())
print("Dataset2 columns:", df2.columns.tolist())
print("Dataset3 columns:", df3.columns.tolist())
print("Counts:", len(df1), len(df2), len(df3))

columns = ["question", "background", "objective", "conclusion"]
df3 = df3[columns]
print("Dataset3 columns:", df3.columns.tolist())

Dataset1 columns: ['instruction', 'input', 'output', '__index_level_0__']
Dataset2 columns: ['output', 'input', 'instruction']
Dataset3 columns: ['question', 'background', 'objective', 'conclusion', 'verdicts', 'strength', 'label', 'category']
Counts: 239357 52002 2786
Dataset3 columns: ['question', 'background', 'objective', 'conclusion']

In [2]:
df3_mapped = pd.DataFrame()
df3_mapped["instruction"] = df3["question"].apply(lambda x: x.strip() if isinstance(x, str) else "")
df3_mapped["input"] = df3.apply(
    lambda row: "\n".join(
        filter(
            None,
            [
                row["background"].strip() if isinstance(row["background"], str) else "",
                row["objective"].strip() if isinstance(row["objective"], str) else "",
            ],
        )
    ),
    axis=1,
)
df3_mapped["output"] = df3["conclusion"].apply(lambda x: x.strip() if isinstance(x, str) else "")

In [3]:
#
# REMOVE QUOTATION MARKS + MERGE
#

df2 = df2.applymap(lambda x: x.strip('"').strip("'") if isinstance(x, str) else x)
df1 = df1.applymap(lambda x: x.strip('"').strip("'") if isinstance(x, str) else x)
df = pd.concat([df1, df2, df3_mapped], ignore_index=True)
df.drop("__index_level_0__", inplace=True, axis=1)

C:\Users\mati\AppData\Local\Temp\ipykernel_15384\905213411.py:5: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df2 = df2.applymap(lambda x: x.strip('"').strip("'") if isinstance(x, str) else x)
C:\Users\mati\AppData\Local\Temp\ipykernel_15384\905213411.py:6: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df1 = df1.applymap(lambda x: x.strip('"').strip("'") if isinstance(x, str) else x)

In [4]:
#
# REMOVE EMPTY ROWS
#


def removeEmpty(df):
    df["instruction"].replace("", np.nan, inplace=True)
    df["input"].replace("", np.nan, inplace=True)
    df["output"].replace("", np.nan, inplace=True)
    return df.dropna()


print(f"Before removal {len(df)}")
df_cleaned = removeEmpty(df)
print(f"After removal {len(df_cleaned)}")

pd.concat([df_cleaned, df]).drop_duplicates(keep=False)

Before removal 294145
After removal 293725

C:\Users\mati\AppData\Local\Temp\ipykernel_15384\1113083008.py:7: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["instruction"].replace("", np.nan, inplace=True)
C:\Users\mati\AppData\Local\Temp\ipykernel_15384\1113083008.py:8: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["input"].replace("", np.nan, inplace=True)
C:\Users\mati\AppData\Local\Temp\ipykernel_15384\1113083008.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["output"].replace("", np.nan, inplace=True)

,instruction,input,output
4924,"If you are a doctor, please answer the medical...",NaN,"hello, 95% of the times' fever in this age gro..."
38944,"If you are a doctor, please answer the medical...",NaN,"hello, i have a seven day cycle. what day woul..."
74180,"If you are a doctor, please answer the medical...",NaN,"hi good day, welcome to chatbot. if your perio..."
77473,Answer this question truthfully,NaN,"I'm sorry, but the given answer ""Symmetric, we..."
80643,"If you are a doctor, please answer the medical...",NaN,hymen with an abnormal sperm count can conceiv...
134711,Answer this question truthfully,NaN,What is the name of the duct that drains the s...
135166,Answer this question truthfully,NaN,There is no vaccine to prevent Lassa fever. Pr...
155338,Answer this question truthfully,NaN,What is the name of the duct that drains the s...
163332,Answer this question truthfully,NaN,Lassa virus commonly involves the liver and re...
172949,"If you are a doctor, please answer the medical...",NaN,hellothanks for query. based n the facts that ...
192011,Answer this question truthfully,NaN,The answer provided is incorrect as it does no...
194219,"If you are a doctor, please answer the medical...",NaN,"hi, thanks for query. you missed period, and i..."
203235,"If you are a doctor, please answer the medical...",NaN,"hi, i can understand your concern. taking an e..."
207191,"If you are a doctor, please answer the medical...",NaN,thanks for your question on chatbot. i can und...
229366,Answer this question truthfully,NaN,"I'm sorry, but the given question and answer c..."
233320,"If you are a doctor, please answer the medical...",NaN,"thanks for your query, i have gone through you..."
233820,Answer this question truthfully,NaN,There seems to be an error in the question and...
242074,Summarize what physiotherapy is.,NaN,Physiotherapy is a branch of healthcare that a...

In [5]:
df_cleaned[df_cleaned.isna().any(axis=1)]

Empty DataFrame
Columns: [instruction, input, output]
Index: []

In [6]:
# #
# # REMOVE NON ENGLISH ROWS
# #

# def is_english(text):
#     try:
#         return detect(text) == "en"
#     except LangDetectException:
#         return False

# mask_non_english = ~df_cleaned["instruction"].apply(is_english)
# removed_non_english = df_cleaned[mask_non_english]

# df_final = df_cleaned[~mask_non_english]

# print("Rows removed (non-English):", len(removed_non_english))
# print(len(df_final))
# removed_non_english.head(50)

In [7]:
# #
# # REMOVE NON ENGLISH ROWS
# #

# from lingua import Language, LanguageDetectorBuilder

# detector = LanguageDetectorBuilder.from_languages(Language.ENGLISH).build()

# def is_english(text):
#     lang = detector.detect_language_of(text)
#     return lang == Language.ENGLISH

# mask_non_english = ~df_cleaned["instruction"].apply(is_english)
# removed_non_english = df_cleaned[mask_non_english]

# df_final = df_cleaned[~mask_non_english]

# print("Rows removed (non-English):", len(removed_non_english))
# print(len(df_final))

# from lingua import Language, LanguageDetectorBuilder

# detector = LanguageDetectorBuilder.from_languages(Language.ENGLISH).build()
# cols = ["instruction", "input", "output"]
# threshold = 0.6

# def row_is_english(row, min_length=50):
#     for c in cols:
#         val = row[c]
#         if isinstance(val, str) and len(val.strip()) >= min_length:
#             conf = detector.compute_language_confidence(val, Language.ENGLISH)
#             if conf < threshold:
#                 return False
#     return True

# mask_english = df_cleaned.apply(row_is_english, axis=1)
# df_final = df_cleaned[mask_english]
# removed_non_english = df_cleaned[~mask_english]

# print("Rows removed (non-English):", len(removed_non_english))
# print(len(df_final))
# removed_non_english.head(50)

In [8]:
#
# DROP DUPLICATES
#
df_final = df_cleaned.drop_duplicates(subset=["instruction", "output", "input"])
print(len(df_final))

293049

In [9]:
df_final[df_final.isna().any(axis=1)]

Empty DataFrame
Columns: [instruction, input, output]
Index: []

In [10]:
import re


def clean_text(text):
    if pd.isna(text):
        return text
    text = re.sub(r"\([A-Z]{2,}\)", "", text)
    text = re.sub(r"\s{2,}", " ", text).strip()
    return text


df_final = df_final.applymap(clean_text)

# for col in ['instruction', 'input', 'output']:
#     df_final[col] = df_final[col].apply(clean_text)

C:\Users\mati\AppData\Local\Temp\ipykernel_15384\117633422.py:12: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_final = df_final.applymap(clean_text)

In [11]:
#
# Drop <noinput>
#


def is_noinput_variant(x):
    if not isinstance(x, str):
        return False
    s = re.sub(r"[^a-zA-Z]", "", x).lower()
    return sorted(s) == sorted("noinput")


if "input" in df_final.columns:
    df_final["input"] = df_final["input"].replace("<noinput>", "").str.strip()
print(len(df_final))


def clean_val(x):
    if not isinstance(x, str):
        return ""
    x = x.strip().strip('"').strip("'")
    if is_noinput_variant(x):
        return ""
    return x


# Final rows not removed
df_final = df_final.applymap(clean_val)
# Final rows removed
# df_fial_stripped = removeEmpty(df_final)

print(len(df_final))
# print(len(df_fial_stripped))

293049

C:\Users\mati\AppData\Local\Temp\ipykernel_15384\88277461.py:28: FutureWarning: DataFrame.applymap has been deprecated. Use DataFrame.map instead.
  df_final = df_final.applymap(clean_val)

293049

In [ ]:
df_final.to_pickle("df_final.pkl")

In [1]:
import pandas as pd
df_final = pd.read_pickle("df_final.pkl")

In [ ]:
mask = df_final.apply(lambda c: c.astype(str).str.contains(r'\b\d+\s*stone\b', case=False, na=False))
mask_exclude = df_final.apply(lambda c: ~c.astype(str).str.contains(r'kidney', case=False, na=False))
final_mask = mask & mask_exclude

stone_units = df_final.where(final_mask)
matches = stone_units.stack()
texts = matches.values.tolist()

print(len(texts))
print("\n".join(texts))

205
Hello My blood pressure has always been completely normal until around 6 weeks ago, where it was 158/110. I am 42, 5 feet 0 high. At this time I weighed 10 1/2 stone, now 10 stone 2 lbs and bp is 132/92. Ive been power walking and working out for 1 1/2 hours per day 6 days per week for the past 6 weeks. My BP has dropped significantly, but the GP wants me to go on lifelong BP tablets - I have completely cut out salt from my diet also - do you think I can get down to normal BP by sustaining my current regime?
i have pain in upper abdomen, very sore to touch. chest pain also, after eating the chest pain is very bad and breathlessness. i have lost 3/4 stone in past 2 months as cannot eat much. had ct scan last wk, waiting on results but feel so weak and ill.
Hi I am 23 5 ft 7 and around 9 stone I have been suffering from stomach problems for around 6 months, in those 6 months my stomache has been in a lot of discomfort, I have been havin at least 4 bowel movements a day which i didnt have before the onset of stomach discomfort. my bowel movements are ever so slightly yellow in colour and feel kind of sticky. I also get a burning sensation throughout my whole digestive system.my stomache is always bloated. In the 6 months I have had this I have had 3 bad outbursts where I was paralysed by the pain and my stomach swelled to the point where i looked at least 6 months pregnant. I am to and from the doctors and given a different diagnosis each time-gall stones, stomache flu, IBS ect. None of which I am satisfied are the answer and im constantly dreading the next outburst. I dont have a history of any kind of stomache problems. Help!
am 5 ft 3 weigh 9 stone in both sides of family there is heart disease and cancer. for about a year now i have had a terrrible pain in the back of my neck right in the middle there is kinda like a movable lump like cartilage or something which is sore my head feel heavy all the time and im tired all the time i have a pretty happy life im a stay at home mum to my three kids but this is getting me down its almost like pressure to back of my head and neck
Im 19, around 5.9. About 12 stone, not really any medical history... I have a strange lump like thing under the skin, on my waistline. I think it may have been a spot, im not sure. It hurt at times, I thought this was just due to the location and the fact I sit a lot putting pressure on it. It gradually subsided to a barely noticeable lump, however theres still a spot like mark there. But its been there for months now.... It looks like spot under the skin. But as I said, its been there for atleast 4 months or so.
hello and welcome to chatbot. as you have 1 stone 7\u00a0mm at the uv junction and an r. distal 8\u00a0mm. stone, its best that you undergo an endoscopic lithography operation, using laser or ultrasound. both the stones can be treated in one session. the patients usually discharged the next day, if there are no complications like, fever, bleeding or any other medical problem. your pain due to the stone will be relieved at once, and there won't be need of any other treatment like homeopathy. remember to chatbot. wish you a speedy recovery.
Hi, I am 24 around 5ft 4 and weigh 8.7 stone.I currently take yasmine contraceptive pill and have had no real medical history other han I recently have had panic attacks around 3 weeks ago. I have noticed that im getting heart palpitations, and my left arm feels tingley and under preasure/numb. i am concerned as my legs swell up really bad and are tender to touch, i have also been feeling very tired and slightly faint at times?
I am a 37year old women, diagnosed a couple of years ago with sinus tachycardia , no treatment, gave up smoking two years ago, 3 stone overweight. Past week have woken up with jaw pain on my left side, which abates during the day. No history of clenching teeth nor grinding when asleep, slight discomfort in left elbow and shoulder, but not sure if I would have noticed if not for the jaw pain, concerned it could be heart related. Father had heart attack at 51. Or is this jaw pain dental related?
Hi, I have recently had a very low Platelet count of 25.000, i also have a very large mass of very dark large bruises predominantly to the back of my left thigh although there are others in different areas. I am 48 years old and weight 13.5 stone. I was previously diagnosed with breat cancer on 7th July 2015 resuting in surgery, chemotherapy and Raiotherapy. How high is the risk on me having developed cancer of the blood or bone. I have tried to speak to the Haematology department to get some reassurance but have been told noone will talk to me.
I am a 21 year old male and wondering what can be wrong with me. For the past two weeks as soon as I eat anything I feel really sick. Sometimes I start vomiting quite badly, I have also had a pain at the top of my rib cage for about a week. It starts off like a hunger pain and then gradually gets worse. I have been bend double with pain today.I am normally fit and healthy am 6ft 2\" tall and weigh 15stone. Any help appreciated. Thanks Sean
I am a 60 yr old male 6ft at 13 stone in weight. Very painful lower back pain, where certain movements can cause a severe pain, virtually bringing me to my knees. Looking at the front of my body in the mirror I see that it has become lopsided in that on hip looks higher than the other, even though I am stood normally... as if my body has been pulled out of shape while this sympton persists. Is this likey to be a muscle or spinal problem?
i have central back pain either side of my spine, and my urine is yellow first thing in the morning, but both get better as the day goes on. i am 59, 5 foot 8 inches, and 11 stone 2 pounds, i have had back pain before, but this is not the same, that was lower back pain, usually caused by twisting wrong or lifting wrong at work, this is central, and feels different, otherwise i am, and always have been in good health.
I have unexplained bruising on my arms and thighs. I also have a raised rash on my left arm and now on my legs . The rash is not itchy or sore, but rough to touch. I am 48 year old female 5ft 1 and 9 stone in weight. I do not feel unwell otherwise . Although I may have the beginnings of a head cold this morning .I have had trouble sleeping and have general aches in my shoulders and back, but don t think it s related to any if the above at all. A couple of months ago, I experienced 3-4 burst blood vessels in my eyes, one after the other. Also unexplained . The optician said my eyes and general health was good and it was nothing to worry about. Shoul I see my GP.?
I have recently been discharged from hospital after which the consultants thought was a heart attack. My trponin were raised. I have had an angiogram and my arteries are excellent, no problems. I know am waiting for an MRI. Can an anxiety attack raise troponins in the blood? I am 43 yrs old 13 stone and 5ft 4ins
Im 29, have recently (in the past year) lost 4 stone in weight and have been exercising regularly. Last week i contracted a stomach bug which has all but gone, but during this time (last Friday) i went to the Doctors and they sent me for a blood test , today i was told my CRP was at a very high level and my FBC was abnormal. I have no idea what this means and was told to go for another blood test. Essentially, can a stomach bug affect these results or not?
I am a 47yr old female, im 5ft 6 tall and weigh 8stone 7lb. I have been suffering nausea on and off for about three weeks, i think i may have lost some weight, even though i am still eating. My skin has become incredibly itchy the last few days. I have been suffering abdominal pro for the last year on and off. I have been seen by my gp who was convinced i have gallstones, i have had a scan and x-rays and no stones have showed up even though i get occasional discomfort under my upper right rib the pain raidiates through to my back.
i have had mirena coil for nealy 3 years and i used to get spots of blood but this month i have had really dark blood and lots of it. what could this be? i am 27, weigh 10stone and am 5f 6. i have been havin pain in my lower stomoch but been tested for pelvic inflamitory and cysts which were all clear
I am a 56 years of age male, i have a white spot on my right nipple, it has now been there for around one month and does not discharge, i am very fit, 5-9 in height and 11 stone in weight, i am in Iraq and it is very hot, i wondered if that had anything to do with it!
hi im 16 and i have really quick mood swings that go straight from happy to angry than sad ? i am losing a lot of weight quickly and i never lose weight and my hair is falling like rain and sometimes my vison is very burled ?? i dont have ant medical history and im around 5 8 weight 9.6 stone. whats wrong with me ?
Hi, for a few months I have suffered, with lower back pain to my right hand side, around where the spine meets the pelvis. This also spreads to my lower stomach again right habd side. I am 177, around 14 1/4 stone, and earlier in the year had a torn ligament in my back.
I am a 59 year old single man. I am 5 feet 10 ins tall and approx 14 stone. I had a heart attack 3 years ago and had two stents fitted and I suffer from angina. I take the usual cocktail of medication and my blood pressure is 119/77 and my pulse is 64 and my colesterol is 4.8, is this normal
I have dry slightly raised white patches ( size of a pencil top at largest) irregular shaped from tiny pinhead upwards, over my feet and legs. they are very unsightly, but do not itch . I am female, 54 years old with dry skin , these however have developed within the last few months. I am over weight by around 2 stone (12/ 2!) But to the best of my knowledge am not diabetic. Hope you can help.
Hi I am 27 years old 6 ft tall and 12.9 stone. I have a soft lump half way between the bottom of my calf and ankle I have had it a year now, my bottom part of my ankle seems to swell if its a hot day, I have a strange dull ache in that area, and now I seem to get pains up the inside of my leg up to my knee. Any ideas?
19 years old,fairly healthy,5\"11 about 13 stone...Chronic back pains for a while now in middle-upper back on the right hand side prodominently.Pain has traveled down to my right arm and under my elbow causing some discomfort...Also have had a burning pain in my lower neck area to the right hand side as well which i have had for a while.I have recently began a office job in which i need to fix this problem as i am only young and it is starting to put me down.Do you know what this could be ? Cheers
Hi - I have been getting upper left back pain for quitea while now - I can t sleep on my back as I feel as if there is something there. I have a 2cm hiatus hernia (diagnosed about a year ago) am about 15 stone , with most weight in mid abdominal region. Was given omeprazole but no benefit to back pain. This now constant. Sometimes helps to eat, sometimes worse on eating - pleass help !! and thanks
Hi,im 26,5ft8 15 stone...no medical history other than usual coughs and colds ,I have a lump halfway up right side of my neck,feels like half a golf ball just sat there,the pain feels like a muscular aching and i have noticed fatigue and tiredness but im not sure if thats just coincedence....no other noted symptoms such as sore throats or swollen glands,problems swallowing etc...
I have a disc bulge. no pressure on nerves. it happened at my 3rd pregnancy. after birth was in severe pain for 4 years could not walk room to room in my own house. little better now heavy lifting starts it off. if i got pregnant again will the bulge get worse.will i be in more pain. will exsiting disc bulge out . has that ever happened to anyone in your experience. i am 5ft 2. weight 8 stone. back problem after last pregnancy disc bulge no pressire on nerves.no other health problems.
Hi, i went to the doctors last week due to having a dull pain in my back below my right shoulder blade, this happened more frequently when turning to the right and breathing in. I went to my local doctor and was told that it was probably pleuracy, and was told not to worry. However this pain has been on and off over a 3 week period, and at this moment in time i get the often stingy feeling in my back. I also keep feeling the need to go for a poo and have a stuffy nose all of a sudden. I dont know if most of this is anxiety or a serious problem, and would like your feedback on the matter until k make another appointment with my gp. Dean palfreman, 21 years old, 5ft9, 11.4 stone
I BELEIVE I HAVE AN INTESTINAL WORM INFESTATION MY SYMPTONS ARE AS FOLLOWS,I HAVE HAD THESE SYMPTONS ON AND OFF FOR AROUND 10 YEARS 1.OFTEN CONSTANT VERY BAD SMELLING GAS 2.DAILY BOUTS OF DIAHORHEA 3 SEVRE WEIGHT LOSS PARTICULARILLY N THE PAST 6 MONTHS 4.PAINFULL,SOMETIMES SHARP ABDOMEN PAINS 5.5SEVRE LETHARGY AND TIREDNESS (IM 34) 6.A LARGE SWELLING ON MY ANAL ENTRANCE 7.DEPRESSION,NO MOTIVATION 8.YELLOWING EYE-WHITES 9.COPPER SMELL TO MY BLOOD 9.BURNING PAIN WHEN PASSING EXCREMENT 10.PAINFULLY THIN,AND GETTING THINER 11.HORRENDOUS BREATH 12.UNABLE TO MAINTAIN AN ERECTION FOR LONG 13.AUDIBLE MOVEMENTS IN MY STOMACH AREA OFTEN 14.ITCHY RASHES ON MY ARMS/legs AND BUTTOCKS I WOULD GREATLY APPRECIATE YOUR OPINION ON THIS MATTER,I LIVE IN A VERY POOR AREA IN LONDON AND THE LOCAL DOCTORS ARE NOT WELL TRAINED AND WILL NOT TAKE MY CONDITION SERIOUSLY . I AM 6FT 3INCHES AND WEIGH 10 STONE,IM 34. DAMION MCLEAN
I am 64 yrs old, 5foot 4inches and weigh 9 stone 4lb and i am female. I have been suffering with anxiety for about 5 weeks and this has caused high blood pressure and a high heart rate. Yesterday I started propranolol 10 mg 2 daily. I have been feeling a bit sick and a bit light headed is this normal. I am not very good at taking tablets and I must admit that these ones frighten me a bit as it seems as though they are difficult to come off. My heart rate has come down from 108 to 80 but the blood pressure seems high still.
Hello i have recently had a 24 hour heart monitor and it found that my heart was beating from 50bpm to 130bpm then going back down again.I am 38 year old woman with a family heart history on my fathers side. I am 5foot 7 and weigh 10stone 11lb.I am waiting for an Eco-cariogram but my palputations are happening more frequently what should i do?
I feel extremely unwell in the early morning at about 5.30 when in bed. There is a degree of fluttery heart beat but I am in no pain. On rising, I feel faint and light headed for a couple of hours. I am 67 years old, male. Weight 15stone,height 5ft 10 inches.Only significant medical history is that I have had an ileostomy for about 17 years. After operations for this, I have developed low blood pressure and been anaemic.At present, I do not think either of these conditions apply but I do tire easily at times.
Hi I m Age 40 14.5 stone , after walking around London 2 days ago when I returned to the hotel my groin hurt, this has now turned into a burning sensation, I assume neurological pain in my pubis region near the lower shaft of my penis, I also have a sensation almost feels like I m bruised on my outer left thigh which is rather tender to touch.
my age is 49 im 5ft 4in 16 stone, i have inactive thyroid, i have misscarried 3 time, that why i went online for drugs to help me try again, but all of a sudden my period stop at the end of october, i have thease tablets called fertomid-50, i have no clue on how to take them, also there was no dos or dont that came with them, just the tablet on its own. what are my chances and how would i take them, cos i have now stop bleeding.
I am shivery, have loss of appetite, heavy eyes and feel very weak. The hospital I work in has diagnosed patients and some staff with TB that are in a ward which I am not in contact with. I am a 42 year old female who is diabetic, who is prone to bowls under my arm but I am on medication for this. I use insulin once in the evening and take all the usual medicines also for my diabetes, weight about 11.2 stone and height 5.3. Thank-you.
Hello, I am 32yr female,5ft4,9 stone always up and down with weight due to eating disorder in past and still struggle to eat proper meals daily,non smoker,hardly drink. I have a phobia of swallowing my tonuge the thought scares me. I can have panic attacks eg
I got swollen glands above my penis to the left and right,almost at the same time I got pshoriasas on the soles of my feet and the palm of my hands with severe Rosea..have tried everything to no avail otherwise Iam quite healthy,I did loose a lot of weight as I lost appitide maybe 2 stone,but have regained some of the weight
I have a small lump under my chin and im going the doctors to get it checked tomorrow but today for some reason my four front teeth are really hurting, like an annoying pain but bearable just really sensitive it feels like do you think these are anything to do with each other? I am 18 about 8 stone and 5 foot 5
my husband was being sick all day yestoday not today just feels sick he has a really bad headache since yestoday morning he says hes week and hurts all over though mostly his right side chest this was the first symptom he is 5foot 6 and weighs 8 stone 4 ish he is 39 yrs and is fit and active though does have a week bladder which he takes triopside for think thats what there called
hi i have recently had 2 lft tests under taken,the first test my ggt was 900,got my second test 6 weeks later and my lft results were back to normal.i was drinking spirits and beer every day for 10 years,and after my first liver test i reduced my alchol down to 2 shandies a week,and my lft was back to normal,is it still safe to drink a couple of shandies per week.im 44 years and 10 10 high and 11 stone.thanks stephen..
Hi back in 2009 i was diagnosed with wolf parkinsons white syndrome and i had to ablations to correct it. i am a 38 year old male of 12 stone and 5ft 11 tall. over the past few months my heart has been skipping beats then stopping for a 2nd then starting again. while all this is going on i am very lite headed and with a slight pain in my chest. sometimes if i walk more than a 100 yards thats when it starts and can sometimes last for about 20 to 30 minutes. i recently went to my doctor who checked my blood pressure which was 185/ 112 so she gave me lisinapril 5mg which i take 2 a day but i still keep getting these skipped beats and dizziness.
Hi. Im a 19 year old female about 5ft 6inches and about 11 stone 7lbs. I have had a history of low self-esteem and did see a Psychologist for a period of time. This was a few years ago though. Recently, I have started to develop erratic mood swings, going from happy to fed up, angry or sad in a second. Im constantly tired and lack energy and sometimes develop bad headaches and some sickness during the afternoon or evening.
Hello, in december 2011, I had a roux-en-y bypass. I have lost 12 stone since then (73% of my excess weight) and my BMI is now below the maximum stated by my OB/GYN for help with infertility. Is there anything I can do to further increase my weight loss, which has started to slow? Also, I have been reading about a supplement called Ovablend (formerly PCOS blend) - would this help? Would Soy Isoflavones help also? Thank you.
Hi name is Derek i am 50yrs old and have been taking dihydrocodiene for approx 12yrs up to 600mg per day my questiston is what is the best way to come off them.i am 5ft 10 inches in height and weigh just under 8 stone. your help in this matter would be most appreciated.
hi i am 18 and 5 foot 4 and weigh 12.5 stone i have been having weird chest pains that feel like my blood is having trouble pumping though my heart. also the chest pains are going up my chest in to my neck when i breath in and i have a metallic taste in the back of my trout is this anything to worry about should i make a doctors appointment ?

In [ ]:
rows_to_drop = final_mask.any(axis=1)

df_cleaned = df_final[~rows_to_drop]

print(len(df_cleaned))

292844

In [ ]:
from generate_jsonl import generate_gemini_jsonl_batches_from_df

columns = ["instruction", "input", "output"]
generate_gemini_jsonl_batches_from_df(df_cleaned, "medical_df", columns, 30000)